### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by rubendibattista** [skyward-er/skyward-matlab-rocket-simulator#2]
The README file must be updated to reflect the new changes in the code.

**Comment by rubendibattista** [comment]
@salvatoreab Do not forget to keep the `README.md` updated ;) 

If you need help let me know.

**Comment by rubendibattista** [comment]
Hello, can you please provide a `README` for the code? I'm told my students here in France to use this code for their rocket so it would be cool if they could actually do that. :)

**Comment by lucafc** [comment]
> Hello, can you please provide a `README` for the code? I told my students here in France to use this code for their rocket so it would be cool if they could actually do that. :)
Uploaded

**Comment by rubendibattista** [comment]
Not a great idea to have a `pdf` as a documentation that is not versioned in the git repository, but just stored as a binary. 

What I suggest you is to store the documentation in the repository so it stays there... You can write the documentation in Markdown and then, if needed for a report, transform it in pdf using for example. The markdown should support LaTeX expression also. 

In any case it's up to you... Thanks for the pdf.
